# Generated by Django 3.1.5 on 2021-01-29 13:22

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='IPADDR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_addr', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ShareImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='share_images')),
                ('result', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images')),
                ('result', models.TextField(default='')),
                ('ip_addr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='endpoints.ipaddr')),
            ],
        ),
        migrations.CreateModel(
            name='FoodPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='foodposts')),
                ('address', models.TextField()),
                ('phone_no', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=55)),
                ('coordinates', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('price', models.CharField(max_length=5)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='endpoints.emuser')),
            ],
        ),
    ]
